plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 33
    buildToolsVersion "33.0.2"

    defaultConfig {
        applicationId "org.tvplayer.app"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 21
        versionName "2.0.1"
        multiDexEnabled true
        ndk {
            abiFilters "arm64-v8a"
        }
        setProperty("archivesBaseName", "TV-go-android-arm64-v${versionName}")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "TV-go-v${variant.versionName}-android-arm64-${variant.buildType.name}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
}
